// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB55SyTTKTTtPHZj0Ez1rfNPb_bKGoJx3E',
    appId: '1:399376595463:web:b20494d06fd31feb6908a2',
    messagingSenderId: '399376595463',
    projectId: 'notifications-3b64f',
    authDomain: 'notifications-3b64f.firebaseapp.com',
    storageBucket: 'notifications-3b64f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4s00lMlwWken9B5-tDr7vq3y1m34hwVw',
    appId: '1:399376595463:android:eece5bb4fddd02046908a2',
    messagingSenderId: '399376595463',
    projectId: 'notifications-3b64f',
    storageBucket: 'notifications-3b64f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH-eKay0APzwou_bxORZaCYHdp8loVw84',
    appId: '1:399376595463:ios:5208b48a23dfa8af6908a2',
    messagingSenderId: '399376595463',
    projectId: 'notifications-3b64f',
    storageBucket: 'notifications-3b64f.appspot.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH-eKay0APzwou_bxORZaCYHdp8loVw84',
    appId: '1:399376595463:ios:5208b48a23dfa8af6908a2',
    messagingSenderId: '399376595463',
    projectId: 'notifications-3b64f',
    storageBucket: 'notifications-3b64f.appspot.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB55SyTTKTTtPHZj0Ez1rfNPb_bKGoJx3E',
    appId: '1:399376595463:web:e258fd3d20941a4f6908a2',
    messagingSenderId: '399376595463',
    projectId: 'notifications-3b64f',
    authDomain: 'notifications-3b64f.firebaseapp.com',
    storageBucket: 'notifications-3b64f.appspot.com',
  );
}
